server:
  port: 9999
  servlet:
    context-path: /batch
spring:
  banner:
    charset: UTF-8
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: EOD BATCH IMPORT
  batch:
    job:
      enabled: false
#    jdbc:
#      initialize-schema: always
#      table-prefix: cfg_job_
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
logging:
  config: classpath:log4j2-spring-dev.xml
app:
  csv:
    filepath: D:\Workspace\Project\SpringBatchEODImport\src\main\resources\data\eod_import.csv  # CSV 文件路径（注意大文件时建议使用流式读取）
    chunkSize: 1000         # Chunk 大小，可根据实际情况调整
